version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  assignees:
  - uditkarode
  ignore:
  - dependency-name: com.arthenica:mobile-ffmpeg-audio
    versions:
    - "> 4.3.1.LTS, < 5"
  - dependency-name: com.arthenica:mobile-ffmpeg-audio
    versions:
    - "> 4.4.LTS, < 5"
  - dependency-name: org.jetbrains.kotlinx:kotlinx-coroutines-core
    versions:
    - "> 1.3.9, < 1.4"
